# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

orbs:
  eks: tiendanube/eks@1.0.0
version: 2.1
workflows:
  deploy:
    jobs:
      - eks/deploy:
          cluster_name: ash
          region: ap-south-1
          steps:
            - run:
                command: |
                  kubectl apply -f bundle.yml
                  kubectl apply -f deployment.yml
