jobs:
  test-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
        default: thri
    steps:
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          command: |
            sudo apt-get install kubectl --classic && kubectl get services
          name: Test Cluster
version: 2.1
orbs:
  aws-eks: circleci/aws-eks@0.1.0
  kubernetes: circleci/kubernetes@0.2.0
workflows:
  deployment:
    jobs:
      - test-cluster:
          cluster-name: thri
